apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: resource-limit
spec:
  crd:
    spec:
      names:
        kind: resource-limit
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package limit
        check_zero(x) {
          to_number(regex.split("[a-zA-Z]+", x.resources.limits.cpu)[0]) > 0
          to_number(regex.split("[a-zA-Z]+", x.resources.requests.cpu)[0]) > 0
          to_number(regex.split("[a-zA-Z]+", x.resources.limits.memory)[0]) > 0
          to_number(regex.split("[a-zA-Z]+", x.resources.requests.memory)[0]) > 0
        }
        violation[{"msg": msg}]{
          ctr_list := input.review.object.spec.template.spec.containers
          some i
          ctr := ctr_list[i]
          not check_zero(ctr)
          msg = sprintf("%v containers 'resource' fields has Invalid value: must be greater than to'0'", [ctr.name])
        }